# Diamond Atari Games
type = "Lucid"
entrypoint = "lucid_v1.dweam_game:LucidGame"
repo_link = "https://github.com/soniccodes/lucid-v1/"
thumbnail_dir = "thumbnails"

# Game-specific metadata
[games.minecraft]
title = "Lucid Minecraft"
description = "Block-based sandbox survival game"
tags = ["First Person", "Minecraft"]

[games.minecraft.buttons]
"â¬†ï¸ Forward" = "W"
"â¬‡ï¸ Backward" = "S"
"â¬…ï¸ Left" = "A"
"â¡ï¸ Right" = "D"
" Jump" = "Space"
"ğŸ—¡ï¸ Attack" = "Left Click"
"ğŸ›¡ï¸ Use" = "Right Click"
